# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8425aee167cec69f07a9a7be96443a54c3b2e52b97221b2dc18bad9a64cb96c1e7c0a16bc3fd256bf552d26d98c5f585b625b5fbab9e427e2493acf2c3671175

test:
  secret_key_base: a9c864b149706a861b3c337299064843529680e83a9c8c7ddc3e3245cd058881bcf6403037a64e39cead9043ab9298339f28e8f558c74ca65a784abb604bf232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
